# Generated by Django 5.2.12 on 2026-03-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="table",
            old_name="count_of_seats",
            new_name="capacity",
        ),
        migrations.AddField(
            model_name="hall",
            name="capacity",
            field=models.PositiveIntegerField(default=0, verbose_name="Количество сидячих мест"),
        ),
        migrations.AddField(
            model_name="hall",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Статус зала"),
        ),
    ]
