# Generated by Django 5.2.12 on 2026-03-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0003_alter_table_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Имя сотрудника",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Имя сотрудника",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("Директор", "Директор"),
                            ("Управляющий", "Управляющий"),
                            ("Администратор", "Администратор"),
                            ("Шеф-повар", "Шеф-повар"),
                            ("Су-шеф", "Су-шеф"),
                            ("Мастер гриля", "Мастер гриля"),
                            ("Повар", "Повар"),
                            ("Шеф-кондитер", "Шеф-кондитер"),
                            ("Метрдотель", "Метрдотель"),
                            ("Сомелье", "Сомелье"),
                            ("Старший официант", "Старший официант"),
                            ("Официант", "Официант"),
                            ("Бармен", "Бармен"),
                            ("Хостес", "Хостес"),
                        ],
                        max_length=40,
                        verbose_name="Занимаемая должность",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="team_members/"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Описание сотрудника",
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
    ]
