# Generated by Django 5.2.12 on 2026-03-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_teammember"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="position_department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Начальство", "Начальство"),
                    ("Кухня", "Кухня"),
                    ("Зал", "Зал"),
                ],
                max_length=40,
                null=True,
                verbose_name="Подразделение",
            ),
        ),
    ]
