# Generated by Django 5.2.12 on 2026-03-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0005_teammember_position_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=1255,
                null=True,
                verbose_name="Описание сотрудника",
            ),
        ),
    ]
