# Generated by Django 5.2.12 on 2026-03-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_remove_event_hall"),
        ("restaurants", "0006_alter_teammember_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="hall",
        ),
        migrations.DeleteModel(
            name="Hall",
        ),
    ]
