# Generated by Django 5.2.12 on 2026-03-23 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_temporaryuser_customuser_email_confirmed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="pr_children",
        ),
    ]
