# Generated by Django 5.2.12 on 2026-03-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_customuser_pr_children"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(default=8999999999, max_length=20),
        ),
    ]
