# Generated by Django 5.2.12 on 2026-03-25 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Возрастная группа"),
                ),
                ("from_age", models.IntegerField(verbose_name="Возраст-порог")),
                ("before_age", models.IntegerField(verbose_name="Возраст-потолок")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Код группы"),
                ),
            ],
            options={
                "verbose_name": "Возрастная группа",
                "verbose_name_plural": "Возрастные группы",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="age_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.agegroup",
            ),
        ),
    ]
