# Generated by Django 5.2.12 on 2026-03-25 12:57

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_agegroup_customuser_age_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(2026, 3, 25, 12, 57, 49, 500431, tzinfo=datetime.timezone.utc),
                verbose_name="Дата рождения",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(max_length=20),
        ),
    ]
