# Generated by Django 5.2.12 on 2026-03-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_customuser_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="birth_date",
            field=models.DateField(verbose_name="Дата рождения"),
        ),
    ]
