# Generated by Django 5.2.12 on 2026-03-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_customuser_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporaryuser",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
    ]
