# Generated by Django 5.2.12 on 2026-03-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_temporaryuser_birth_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="temporaryuser",
            name="birth_date",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
    ]
