# Generated by Django 5.2.12 on 2026-03-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Возрастная группа"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Код группы"),
                ),
            ],
            options={
                "verbose_name": "Возрастная группа",
                "verbose_name_plural": "Возрастные группы",
            },
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="events/",
                        verbose_name="Постер",
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=10000, verbose_name="Описание"),
                ),
                (
                    "price",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "min_age",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Возрастное ограничение",
                    ),
                ),
                (
                    "date_start",
                    models.DateTimeField(null=True, verbose_name="Дата начала"),
                ),
                (
                    "max_people",
                    models.PositiveIntegerField(default=50, verbose_name="Макс. кол-во человек"),
                ),
                (
                    "recommend_audit_gender",
                    models.CharField(
                        blank=True,
                        choices=[("man", "Мужчина"), ("woman", "Женщиина")],
                        max_length=15,
                        null=True,
                        verbose_name="Целевой пол",
                    ),
                ),
                (
                    "recommend_audit_ph_children",
                    models.CharField(
                        blank=True,
                        choices=[("Yes", "Есть дети"), ("No", "Нет детей")],
                        max_length=15,
                        null=True,
                        verbose_name="Целевая аудитория (дети)",
                    ),
                ),
                (
                    "hall",
                    models.ManyToManyField(blank=True, to="restaurants.hall", verbose_name="Зал проведения"),
                ),
                (
                    "recommend_audit_age",
                    models.ManyToManyField(
                        blank=True,
                        to="events.agegroup",
                        verbose_name="Целевые возрастные группы",
                    ),
                ),
            ],
            options={
                "verbose_name": "мероприятие",
                "verbose_name_plural": "мероприятия",
                "ordering": ["-date_start"],
            },
        ),
    ]
