# Generated by Django 5.2.12 on 2026-03-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="now_people",
            field=models.PositiveIntegerField(default=50, verbose_name="Актуальное количество человек кол-во человек"),
        ),
    ]
