# Generated by Django 5.2.12 on 2026-03-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_events_now_people"),
        ("restaurants", "0003_alter_table_number"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Events",
            new_name="Event",
        ),
    ]
