# Generated by Django 5.2.12 on 2026-03-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_rename_events_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_archive",
            field=models.BooleanField(default=False),
        ),
    ]
