# Generated by Django 5.2.12 on 2026-03-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_event_is_archive"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="price",
        ),
    ]
