# Generated by Django 5.2.12 on 2026-03-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_remove_event_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="max_people",
        ),
        migrations.AlterField(
            model_name="event",
            name="now_people",
            field=models.PositiveIntegerField(default=50, verbose_name="Актуальное количество человек"),
        ),
    ]
