# Generated by Django 5.2.12 on 2026-03-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_remove_event_max_people_alter_event_now_people"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="hall",
        ),
    ]
