# Generated by Django 5.2.12 on 2026-03-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_remove_event_recommend_audit_ph_children"),
    ]

    operations = [
        migrations.AddField(
            model_name="agegroup",
            name="before_age",
            field=models.IntegerField(default=0, verbose_name="Возраст-потолок"),
        ),
        migrations.AddField(
            model_name="agegroup",
            name="from_age",
            field=models.IntegerField(default=0, verbose_name="Возраст-порог"),
        ),
    ]
