# Generated by Django 5.2.12 on 2026-03-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_agegroup_before_age_agegroup_from_age"),
        ("users", "0005_agegroup_customuser_age_group"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AgeGroup",
        ),
        migrations.AlterField(
            model_name="event",
            name="recommend_audit_age",
            field=models.ManyToManyField(
                blank=True,
                to="users.agegroup",
                verbose_name="Целевые возрастные группы",
            ),
        ),
    ]
