services:

  db:
    env_file:
      - .env
    image: postgres:17
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  redis:
    env_file:
      - .env
    image: redis:alpine
    ports:
      - "6379:6379"


  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - db

  worker:
    build: .
    env_file:
      - .env
    command: celery -A config worker -l INFO
    volumes:
      - .:/app
      - ./media:/app/media
    depends_on:
      - redis
      - db

  beat:
    build: .
    env_file:
      - .env
    command: celery -A config beat -l INFO
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
  media:
