# Generated by Django 5.2.12 on 2026-03-16 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guest_name",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Имя гостя"),
                ),
                (
                    "guest_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Телефон гостя",
                    ),
                ),
                (
                    "guest_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email гостя",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата бронирования")),
                ("start_time", models.TimeField(verbose_name="Время начала")),
                ("end_time", models.TimeField(verbose_name="Время окончания")),
                (
                    "guests",
                    models.PositiveSmallIntegerField(verbose_name="Количество гостей"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Ожидает подтверждения"),
                            ("CONFIRMED", "Подтверждена"),
                            ("CANCELLED", "Отменена"),
                            ("EXPIRED", "Просрочена"),
                            ("COMPLETED", "Завершена"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Статус бронирования",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Время создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Время последнего изменения"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Время истечения временной брони",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="restaurants.table",
                        verbose_name="Столик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
                "ordering": ["date", "start_time"],
            },
        ),
    ]
