# Generated by Django 5.2.12 on 2026-03-24 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_initial"),
        ("restaurants", "0007_remove_table_hall_delete_hall"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="restaurants.table",
                verbose_name="Столик",
            ),
        ),
    ]
