# Generated by Django 5.2.12 on 2026-03-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_alter_reservation_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
    ]
