# Generated by Django 5.2.12 on 2026-03-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_reservation_reminder_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="comment_admin",
            field=models.CharField(
                blank=True,
                max_length=3000,
                null=True,
                verbose_name="Обратная связь по брони",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="comment_user",
            field=models.CharField(
                blank=True,
                max_length=3000,
                null=True,
                verbose_name="Комментарий пользователя",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="score",
            field=models.CharField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                max_length=20,
                null=True,
                verbose_name="Оценка посещения",
            ),
        ),
    ]
